  steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/csci5409-389802/docker/container202:latest'
      - './'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/csci5409-389802/docker/container202:latest'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - container
      - clusters
      - get-credentials
      - ${_CLUSTER_NAME}  
      - --zone
      - ${_COMPUTE_ZONE}
  - name: "gcr.io/cloud-builders/gke-deploy"
    id: deploy-gke
    args:
      - run
      - --filename=deployment.yaml
      - --location=${_COMPUTE_ZONE}
      - --cluster=${_CLUSTER_NAME}
  # - name: 'gcr.io/cloud-builders/kubectl'
  #   id: update-container-1
  #   args:
  #   - set
  #   - image
  #   - deployment/container-1
  #   - conatainer-1=${_RV}
  #   env:
  #   - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
  #   - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
  #   waitFor:
  #   - deploy-gke
  substitutions:
    _RV: us-central1-docker.pkg.dev/csci5409-389802/docker/container202:latest
    _CLUSTER_NAME: standard-cluster
    _COMPUTE_ZONE: us-central1-c
